Create sweep with ID: mk06ihr7
Sweep URL: https://wandb.ai/pingu-73/question_three_two_housing/sweeps/mk06ihr7
[34m[1mwandb[0m: [33mWARNING[0m Changes to your `wandb` environment variables will be ignored because your `wandb` session has already started. For more information on how to modify your settings with `wandb.init()` arguments, please refer to [34m[4mhttps://wandb.me/wandb-init[0m.
Traceback (most recent call last):
  File "/Users/dikshant/Desktop/college/smai/env/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dikshant/Desktop/college/smai/env/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'hidden_layer_sizes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dikshant/Desktop/college/smai/smai-m24-assignments-pingu-73/assignments/3/a3.py", line 179, in question_three
    hidden_layer_sizes=config.hidden_layer_sizes,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dikshant/Desktop/college/smai/env/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'hidden_layer_sizes'
